spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${port}/${DBname}
    password: ${password}
    username: ${username}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
